#name your workflow
name: My test workflow
#event trigger
on: [push]

jobs: 
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, Github Actions !"
    test_integration:
        needs: say-hello
        runs-on: ubuntu-latest
        steps:
          - name: checkout this repo 
            uses: actions/checkout@v3
          - name: install dependiceies
            run : sudo apt install -y build-essential python3
          
          - run: pwd
          
          - name: Run test
            run: python3 test.py


    

    